<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Bankim" failures="2" tests="2" name="Test(failed)" time="0.028" errors="0" timestamp="2022-09-17T09:00:43 CDT">
  <testcase classname="com.usa.failTestRun.Class_B" name="getTest4" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.usa.failTestRun.Class_B.getTest4(Class_B.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTest4 -->
  <testcase classname="com.usa.failTestRun.Class_C" name="getTest8" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.usa.failTestRun.Class_C.getTest8(Class_C.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getTest8 -->
  <testcase classname="com.usa.failTestRun.Class_B" name="getTest5" time="0.0">
    <ignored/>
  </testcase> <!-- getTest5 -->
  <testcase classname="com.usa.failTestRun.Class_B" name="getTest6" time="0.0">
    <ignored/>
  </testcase> <!-- getTest6 -->
  <testcase classname="com.usa.failTestRun.Class_C" name="getTest7" time="0.0">
    <ignored/>
  </testcase> <!-- getTest7 -->
  <testcase classname="com.usa.failTestRun.Class_C" name="getTest9" time="0.0">
    <ignored/>
  </testcase> <!-- getTest9 -->
</testsuite> <!-- Test(failed) -->
